stages:
  - build

image: 'node:latest'

before_script:
  - apt update -y
  - corepack enable pnpm
  - mkdir public

build:pretty-check:
  stage: build
  script:
    - pnpm i
    - pnpm pretty-check

build:local:
  stage: build
  script:
    - pnpm build-local
    - mkdir .next/standalone/public && cp -aR public/* .next/standalone/public
    - mkdir .next/standalone/public/_next && cp -aR .next/static/ .next/standalone/public/_next
    - 'mv .next/standalone/ public/'
  artifacts:
    paths:
      - public/standalone
