categories: Categories
search: Search...
searchFirst: First search, index file loading, please wait...
searchNoResult: No result
searchFilesNotfound: The search.xml file was not found, please refer to：
searchServiceErrors: The request failed, Try to refresh the page or try again later.
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
newer: Newer
older: Older
share: Share
powered_by: Powered by
rss_feed: RSS Feed
category: Category
tag: Tag
catalog: Contents
pinned: Pinned
updateTime: Update time
about: About
friend: Friend
